export function renderChat(host){
  const url = new URL(location.href);
  const prefill = (url.hash.split('?')[1] ? new URLSearchParams(url.hash.split('?')[1]).get('prefill') : '') || '';

  host.innerHTML = `
    <div class="page-shell">
      <h2 class="card-title" style="margin-bottom:10px;">AI Research Assistant</h2>
      <div class="panel" style="min-height:420px; display:flex; flex-direction:column;">
        <div id="thread" style="flex:1; display:flex; flex-direction:column; gap:10px; overflow:auto;">
          <div class="msgrow"><span class="avatar"></span><div class="msg bot">Welcome to AstroQuery AI Assistant! Ask a question to search research databases.<div class="time">now</div></div></div>
        </div>
        <div class="row" style="margin-top:12px;">
          <textarea id="chatInput" placeholder="Ask me about astronomical research…" rows="2" class="input" style="flex:1; padding:10px 12px; border-radius:10px; border:1px solid var(--stroke); background:#0b1428; color:#eaf6ff;"></textarea>
          <button id="sendBtn" class="btn">Send</button>
        </div>
        <div class="muted" style="font-size:12px; margin-top:6px;">Press Enter to send • Shift+Enter for new line</div>
      </div>
    </div>
  `;

  const input = host.querySelector('#chatInput');
  const send  = host.querySelector('#sendBtn');
  const thread= host.querySelector('#thread');


  function add(msg, who='bot', mode='RAG'){
    const row = document.createElement('div');
    row.className='msgrow';
    if (who==='bot'){
      const hazardBadge = mode === 'AI'
        ? `<div class="ai-hazard-badge" title="This response was generated by an AI model">
             <svg width="12" height="12" viewBox="0 0 24 24" fill="none" style="vertical-align:middle;">
               <path d="M12 2L2 20h20L12 2z" stroke="currentColor" stroke-width="2" fill="none"/>
               <path d="M12 9v4M12 17h.01" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>
             </svg>
             Generated by AI
           </div>`
        : '';
      row.innerHTML = `<span class="avatar"></span><div class="msg bot">${hazardBadge}${msg}<div class="time">${new Date().toLocaleTimeString()}</div></div>`;
    } else {
      row.innerHTML = `<div class="msg mine">${msg}<div class="time">${new Date().toLocaleTimeString()}</div></div>`;
    }
    thread?.appendChild(row);
    thread.scrollTop = thread.scrollHeight;
  }

  send?.addEventListener('click', async ()=>{
    const v = input.value.trim();
    if(!v) return;
    add(v,'mine');
    input.value='';
    
    // Show loading state
    const loadingRow = document.createElement('div');
    loadingRow.className='msgrow';
    loadingRow.innerHTML = `<span class="avatar"></span><div class="msg bot">Thinking...<div class="time">now</div></div>`;
    thread?.appendChild(loadingRow);
    thread.scrollTop = thread.scrollHeight;
    
    try {
      const response = await fetch('http://localhost:5000/chat', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          messages: [{ role: 'user', content: v }],
          k: 5
        })
      });
      
      if (!response.ok) {
        throw new Error(`Chat failed: ${response.status} ${response.statusText}`);
      }
      
      const data = await response.json();
      
      // Remove loading message
      loadingRow.remove();
      
      // Add the actual response
      add(data.answer, 'bot', data.mode);
      
      // Show citations if available and response is not "I don't know"
      const isDontKnowResponse = data.answer.toLowerCase().includes("i don't know") || 
                                 data.answer.toLowerCase().includes("i do not know") ||
                                 data.answer.toLowerCase().includes("i'm not sure") ||
                                 data.answer.toLowerCase().includes("i am not sure");
      
      if (data.citations && data.citations.length > 0 && !isDontKnowResponse) {
        const citationsHtml = data.citations.map(citation => 
          `<div class="citation">
            <a href="${citation.link}" target="_blank" rel="noopener noreferrer">${citation.title}</a>
            <span class="citation-meta">${citation.journal} (${citation.year})</span>
          </div>`
        ).join('');
        
        add(`<div class="citations-section">
          <strong>Sources:</strong>
          <div class="citations">${citationsHtml}</div>
        </div>`, 'bot');
      }
      
    } catch (error) {
      // Remove loading message
      loadingRow.remove();
      add(`Sorry, I encountered an error: ${error.message}`, 'bot', 'AI');
    }
  });

  input?.addEventListener('keydown', (e)=>{
    if(e.key==='Enter' && !e.shiftKey){
      e.preventDefault();
      send.click();
    }
  });

  if (prefill){
    input.value=prefill;
    input?.focus();
  }
}
