export const PUBLICATIONS = [
  {
    id:"p1",
    title:"Microgravity Effects on Immune Cells",
    authors:["Nguyen","Khan"],
    year:2019,
    section:"Immune",
    abstract:"Study examining T-cell activation and proliferation under microgravity conditions aboard the ISS.",
    source:"NASA",
    url:"https://example.com/1",
    keywords:["T-cells","ISS"],
    organism:"Human",
    missionId:"ISS-54"
  },
  {
    id:"p2",
    title:"Plant Growth in Space Habitats",
    authors:["Ali","Ramos"],
    year:2021,
    section:"Plants",
    abstract:"Investigation of Arabidopsis thaliana growth patterns under varying light conditions in controlled space environments.",
    source:"DOI",
    url:"https://example.com/2",
    keywords:["Arabidopsis","light"],
    organism:"Arabidopsis thaliana",
    missionId:"PL-09"
  },
  {
    id:"p3",
    title:"Cellular Aging in Microgravity",
    authors:["Chen","Martinez","Lee"],
    year:2018,
    section:"Cellular",
    abstract:"Analysis of telomere shortening and cellular senescence markers in cells exposed to prolonged microgravity.",
    source:"PubMed",
    url:"https://example.com/3",
    keywords:["telomeres","aging","senescence"],
    organism:"Human fibroblasts",
    missionId:"ISS-48"
  },
  {
    id:"p4",
    title:"Genomic Stability Under Space Radiation",
    authors:["O'Brien","Patel"],
    year:2020,
    section:"Genomics",
    abstract:"Comprehensive study of DNA damage and repair mechanisms in cells exposed to cosmic radiation.",
    source:"Nature",
    url:"https://example.com/4",
    keywords:["DNA damage","radiation","repair"],
    organism:"Human lymphocytes",
    missionId:"ISS-61"
  },
  {
    id:"p5",
    title:"Microbial Adaptation to Zero Gravity",
    authors:["Silva","Johnson"],
    year:2017,
    section:"Microgravity",
    abstract:"Study of bacterial behavior and biofilm formation in microgravity environments.",
    source:"PLOS",
    url:"https://example.com/5",
    keywords:["bacteria","biofilm","adaptation"],
    organism:"E. coli",
    missionId:"ISS-50"
  },
  {
    id:"p6",
    title:"Immune Response to Pathogens in Space",
    authors:["Kim","Davis","White"],
    year:2022,
    section:"Immune",
    abstract:"Assessment of innate and adaptive immune responses to viral challenges during long-duration spaceflight.",
    source:"Science",
    url:"https://example.com/6",
    keywords:["immune response","virus","spaceflight"],
    organism:"Human",
    missionId:"ISS-66"
  },
  {
    id:"p7",
    title:"Root Development in Simulated Mars Gravity",
    authors:["Taylor","Brown"],
    year:2023,
    section:"Plants",
    abstract:"Investigation of root gravitropism and architecture under Mars-simulated gravity conditions.",
    source:"Plant Cell",
    url:"https://example.com/7",
    keywords:["roots","Mars","gravity"],
    organism:"Zea mays",
    missionId:"PL-12"
  },
  {
    id:"p8",
    title:"Protein Crystallization in Microgravity",
    authors:["Wilson","Garcia"],
    year:2016,
    section:"Cellular",
    abstract:"Enhanced protein crystal formation for structural biology studies conducted in microgravity.",
    source:"Acta Crystallographica",
    url:"https://example.com/8",
    keywords:["crystallization","protein structure"],
    organism:"Various",
    missionId:"ISS-47"
  },
  {
    id:"p9",
    title:"Gene Expression Changes During Spaceflight",
    authors:["Anderson","Lopez","Zhang"],
    year:2019,
    section:"Genomics",
    abstract:"Transcriptomic analysis revealing differential gene expression patterns in astronauts during missions.",
    source:"Cell",
    url:"https://example.com/9",
    keywords:["transcriptomics","gene expression","astronauts"],
    organism:"Human",
    missionId:"ISS-57"
  },
  {
    id:"p10",
    title:"Bone Density Loss in Microgravity",
    authors:["Thompson","Miller"],
    year:2015,
    section:"Microgravity",
    abstract:"Longitudinal study of bone mineral density changes and countermeasure effectiveness in astronauts.",
    source:"JBMR",
    url:"https://example.com/10",
    keywords:["bone density","osteoporosis","countermeasures"],
    organism:"Human",
    missionId:"ISS-42"
  },
  {
    id:"p11",
    title:"Circadian Rhythm Disruption in Space",
    authors:["Robinson","Lee"],
    year:2021,
    section:"Cellular",
    abstract:"Study of circadian clock gene regulation and sleep patterns during extended space missions.",
    source:"Sleep",
    url:"https://example.com/11",
    keywords:["circadian","sleep","gene regulation"],
    organism:"Human",
    missionId:"ISS-64"
  },
  {
    id:"p12",
    title:"Epigenetic Modifications in Spaceflight",
    authors:["Harris","Moore","Clark"],
    year:2024,
    section:"Genomics",
    abstract:"Analysis of DNA methylation and histone modifications in cells exposed to spaceflight conditions.",
    source:"Epigenetics",
    url:"https://example.com/12",
    keywords:["epigenetics","methylation","histones"],
    organism:"Human",
    missionId:"ISS-70"
  }
];
